name: Build ZMK firmware (overlay)
on:
  workflow_dispatch:
    inputs:
      zmk_repo:
        description: ZMK repo URL (fork or upstream)
        required: true
        default: https://github.com/divnty/zmk
      zmk_ref:
        description: Branch or tag
        required: true
        default: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config (this branch)
        uses: actions/checkout@v4
      - name: Build
        uses: zmkfirmware/action-build@v1
        with:
          zmk_repo: ${{ inputs.zmk_repo }}
          zmk_ref:  ${{ inputs.zmk_ref }}
          config_path: .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware
          path: build/**/*
